packages:
  - packages/**
catalog:
  '@antfu/eslint-config': ^3.8.0
  eslint: ^9.13.0
  lint-staged: ^15.2.10
  simple-git-hooks: ^2.11.1
  esno: ^4.7.0
  typescript: ^5.5.4
  unbuild: ^2.0.0
  vite: ^5.4.2
