import type { ValidatorJSON } from '../server/utils/schemas'
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import process from 'node:process'
import { validatorSchema } from '../server/utils/schemas'

const NETWORKS = ['main-albatross', 'test-albatross'] as const
type Network = (typeof NETWORKS)[number]

async function loadValidatorsForNetwork(rootDir: string, network: Network): Promise<ValidatorJSON[]> {
  const validatorsDir = join(rootDir, 'public', 'validators', network)
  const entries = await readdir(validatorsDir, { withFileTypes: true })
  const files = entries
    .filter(entry => entry.isFile())
    .map(entry => entry.name)
    .filter(name => name.endsWith('.json') && !name.endsWith('.example.json'))
    .sort((a, b) => a.localeCompare(b))

  if (files.length === 0)
    throw new Error(`No validator files found in ${validatorsDir}`)

  const validators: ValidatorJSON[] = []
  for (const file of files) {
    const filePath = join(validatorsDir, file)
    const raw = await readFile(filePath, 'utf8')

    let parsedJson: unknown
    try {
      parsedJson = JSON.parse(raw)
    }
    catch (error) {
      throw new Error(`Invalid JSON at ${filePath}: ${String(error)}`)
    }

    const parsedValidator = validatorSchema.safeParse(parsedJson)
    if (!parsedValidator.success)
      throw new Error(`Invalid validator JSON at ${network}/${file}: ${parsedValidator.error}`)

    validators.push(parsedValidator.data)
  }

  return validators
}

function createManifestSource(validatorsByNetwork: Record<Network, ValidatorJSON[]>): string {
  const serialized = JSON.stringify(validatorsByNetwork, null, 2)
  return `/* eslint-disable style/quotes, style/quote-props, style/comma-dangle */
import type { ValidatorJSON } from '../utils/schemas'

// This file is auto-generated by scripts/generate-validators-bundle.ts.
// Do not edit manually.
export const bundledValidatorsByNetwork = ${serialized} as unknown as Record<'main-albatross' | 'test-albatross', ValidatorJSON[]>
`
}

async function main() {
  const rootDir = resolve(process.cwd())
  const outputDir = join(rootDir, 'server', 'generated')
  const outputFile = join(outputDir, 'validators-bundle.generated.ts')

  const entries = await Promise.all(NETWORKS.map(async network => [network, await loadValidatorsForNetwork(rootDir, network)] as const))
  const validatorsByNetwork = Object.fromEntries(entries) as Record<Network, ValidatorJSON[]>

  await mkdir(outputDir, { recursive: true })
  await writeFile(outputFile, createManifestSource(validatorsByNetwork), 'utf8')
  console.log(`[validators-bundle] generated ${outputFile}`)
}

main().catch((error) => {
  console.error('[validators-bundle] failed to generate bundle')
  console.error(error)
  process.exitCode = 1
})
